; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = willy_release
boards_dir = boards/_boards_json

[env:willy_release]
board = ESP32-S3-DevKitC-1-N8R2
board_build.partitions = custom_8Mb.csv
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
upload_port = COM3
board_build.flash_mode = qio
platform = espressif32@6.7.0
framework = arduino
build_type = release
lib_compat_mode = strict
lib_ldf_mode = deep+
board_build.variants_dir = boards
board_build.filesystem = littlefs
monitor_port = COM3
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize
monitor_dtr = 1
monitor_rts = 1
build_flags = 
	-O2
	-flto
	-DNDEBUG
	-Wl,--strip-all
	-DWILLY_VERSION='"1.0.0"'
	-DCORE_DEBUG_LEVEL=4
	-DLV_TICK_CUSTOM=1
	-DARDUINO_RUNNING_CORE=1
	-DTFT_eSPI_VERSION=2.5.43
	-I lib/mquickjs_headers
	-DEEPROMSIZE=128
	-DLH=8
	-DLW=6
	-ffunction-sections
	-fdata-sections
	-Wl,--print-memory-usage
	-Wl,--gc-sections
	-Wl,--allow-multiple-definition
	-DGIT_COMMIT_HASH='"Homebrew"'
	-DFASTLED_RMT_BUILTIN_DRIVER=1
	-DCONFIG_ASYNC_TCP_STACK_SIZE=4096
	-DCONFIG_ASYNC_TCP_RUNNING_CORE=1
	-DCONFIG_ASYNC_TCP_USE_WDT=0
	-DGEN_MQJS_HEADERS
	-Iinclude
	-Isrc
	-Iboards/ESP32-S3-WROOM-1-N16R8
	-Ilib/HAL
	-Ilib/TFT_eSPI
	-Ilib/TFT_eSPI
	-Wno-narrowing
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DRGB_LED=48
	-DHAS_RGB_LED=1
	-DLED_COUNT=1
	-DLED_TYPE=WS2812B
	-DLED_ORDER=GRB
	-DLED_COLOR_STEP=5
	-DLED_TYPE_IS_RGBW=0
	-DGROVE_SDA=8
	-DGROVE_SCL=17
	-DSPI_SCK_PIN=12
	-DSPI_MOSI_PIN=11
	-DSPI_MISO_PIN=13
	-DSPI_SS_PIN=10
	-DUSE_HSPI_PORT=1
	-DTFT_BL=3
	-DHAS_SCREEN=1
	-DUSER_SETUP_LOADED=1
	-DILI9341_DRIVER=1
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	-DROTATION=1
	-DBACKLIGHT=3
	-DMINBRIGHT=160
	-DTFT_DISPON=0x29
	-DTFT_DISPOFF=0x28
	-DTFT_CS=10
	-DTFT_DC=9
	-DTFT_RST=14
	-DTFT_MOSI=11
	-DTFT_MISO=13
	-DTFT_SCLK=12
	-DTFT_BL=3
	-DTFT_BACKLIGHT_ON=HIGH
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=20000000
	-DSPI_READ_FREQUENCY=10000000
	-DTFT_RGB_ORDER=TFT_BGR
	-DLVGL_USE_DMA=0
	-DHAS_TOUCH=1
	-DTOUCH_CS=15
	-DTOUCH_IRQ=-1
	-DSPI_TOUCH_FREQUENCY=1000000
	-DUSE_TFT_eSPI_TOUCH=1
	-DCONFIG_SPIRAM=1
	-DSDCARD_CS=38
	-DSDCARD_SCK=12
	-DSDCARD_MISO=13
	-DSDCARD_MOSI=11
	-DNRF24_SCK_PIN=12
	-DNRF24_MISO_PIN=13
	-DNRF24_MOSI_PIN=11
	-DNRF24_SS_PIN=16
	-DNRF24_CE_PIN=21
	-DNRF24_CS_PIN=16
	-DNRF24_CS2_PIN=35
	-DNRF24_CE2_PIN=37
	-DCC1101_SCK_PIN=12
	-DCC1101_MISO_PIN=13
	-DCC1101_MOSI_PIN=11
	-DCC1101_SS_PIN=18
	-DCC1101_GDO0_PIN=33
	-DCC1101_GDO2_PIN=34
	-DCC1101_CS_PIN=18
	-DCC1101_GDO0=33
	-DCC1101_GDO2=34
	-DGPS_SERIAL_TX=40
	-DGPS_SERIAL_RX=39
	-DGPS_BAUD=9600
	-DTXLED=1
	-DRXLED=47
	-DLED_ON=HIGH
	-DLED_OFF=LOW
	-DIR_TX_PINS='{{"IR TX", 1}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DIR_RX_PINS='{{"IR RX", 47}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DRF_TX_PINS='{{"M5 RF433T", GROVE_SDA}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DRF_RX_PINS='{{"M5 RF433R", GROVE_SCL}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DI2S_SCK_PIN=41
	-DI2S_WS_PIN=42
	-DI2S_SD_PIN=2
	-DJOY_X_PIN=4
	-DJOY_Y_PIN=5
	-DJOY_BTN_PIN=6
	-DLORA_SCK=12
	-DLORA_MISO=13
	-DLORA_MOSI=11
	-DLORA_CS=19
	-DLORA_RST=20
	-DLORA_DIO0=22
	-DW5500_SCK_PIN=12
	-DW5500_MISO_PIN=13
	-DW5500_MOSI_PIN=11
	-DW5500_SS_PIN=23
	-DW5500_INT_PIN=24
	-DW5500_RST_PIN=25
	-DFP=1
	-DFM=2
	-DFG=3
	-DBTN_ALIAS='"OK"'
	-DLOAD_GLCD=1
	-DLOAD_FONT2=1
	-DLOAD_FONT4=1
	-I C:/Users/leleb/.platformio/packages/framework-arduinoespressif32/libraries/Network/src
	-I $PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries
	-DDEVICE_NAME='"ESP32-S3 DevKitC-1 (Willy)"'
lib_deps = 
	bblanchon/ArduinoJson@^7.4.3
	spacehuhn/SimpleCLI@^1.1.4

[env:willy_debug]
board = ESP32-S3-DevKitC-1-N8R2
board_build.partitions = custom_8Mb.csv
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
upload_port = COM3
board_build.flash_mode = qio
platform = espressif32
framework = arduino
build_type = debug
lib_compat_mode = soft
lib_ldf_mode = deep+
board_build.variants_dir = boards
board_build.filesystem = littlefs
monitor_port = COM3
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize
monitor_dtr = 1
monitor_rts = 1
build_flags = 
	-Os
	-g
	-DWILLY_VERSION='"1.0.0"'
	-DCORE_DEBUG_LEVEL=4
	-DLV_TICK_CUSTOM=1
	-DARDUINO_RUNNING_CORE=1
	-DTFT_eSPI_VERSION=2.5.43
	-I lib/mquickjs_headers
	-DEEPROMSIZE=128
	-DLH=8
	-DLW=6
	-ffunction-sections
	-fdata-sections
	-Wl,--print-memory-usage
	-Wl,--gc-sections
	-Wl,--allow-multiple-definition
	-DGIT_COMMIT_HASH='"Homebrew"'
	-DFASTLED_RMT_BUILTIN_DRIVER=1
	-DCONFIG_ASYNC_TCP_STACK_SIZE=4096
	-DCONFIG_ASYNC_TCP_RUNNING_CORE=1
	-DCONFIG_ASYNC_TCP_USE_WDT=0
	-DGEN_MQJS_HEADERS
	-Iinclude
	-Isrc
	-Iboards/ESP32-S3-WROOM-1-N16R8
	-Ilib/HAL
	-Ilib/TFT_eSPI
	-Ilib/TFT_eSPI
	-Wno-narrowing
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DRGB_LED=48
	-DHAS_RGB_LED=1
	-DLED_COUNT=1
	-DLED_TYPE=WS2812B
	-DLED_ORDER=GRB
	-DLED_COLOR_STEP=5
	-DLED_TYPE_IS_RGBW=0
	-DGROVE_SDA=8
	-DGROVE_SCL=17
	-DSPI_SCK_PIN=12
	-DSPI_MOSI_PIN=11
	-DSPI_MISO_PIN=13
	-DSPI_SS_PIN=10
	-DUSE_HSPI_PORT=1
	-DTFT_BL=3
	-DHAS_SCREEN=1
	-DUSER_SETUP_LOADED=1
	-DILI9341_DRIVER=1
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	-DROTATION=1
	-DBACKLIGHT=3
	-DMINBRIGHT=160
	-DTFT_DISPON=0x29
	-DTFT_DISPOFF=0x28
	-DTFT_CS=10
	-DTFT_DC=9
	-DTFT_RST=14
	-DTFT_MOSI=11
	-DTFT_MISO=13
	-DTFT_SCLK=12
	-DTFT_BL=3
	-DTFT_BACKLIGHT_ON=HIGH
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=20000000
	-DSPI_READ_FREQUENCY=10000000
	-DTFT_RGB_ORDER=TFT_BGR
	-DLVGL_USE_DMA=0
	-DHAS_TOUCH=1
	-DTOUCH_CS=15
	-DTOUCH_IRQ=-1
	-DSPI_TOUCH_FREQUENCY=1000000
	-DUSE_TFT_eSPI_TOUCH=1
	-DCONFIG_SPIRAM=1
	-DSDCARD_CS=38
	-DSDCARD_SCK=12
	-DSDCARD_MISO=13
	-DSDCARD_MOSI=11
	-DNRF24_SCK_PIN=12
	-DNRF24_MISO_PIN=13
	-DNRF24_MOSI_PIN=11
	-DNRF24_SS_PIN=16
	-DNRF24_CE_PIN=21
	-DNRF24_CS_PIN=16
	-DNRF24_CS2_PIN=35
	-DNRF24_CE2_PIN=37
	-DCC1101_SCK_PIN=12
	-DCC1101_MISO_PIN=13
	-DCC1101_MOSI_PIN=11
	-DCC1101_SS_PIN=18
	-DCC1101_GDO0_PIN=33
	-DCC1101_GDO2_PIN=34
	-DCC1101_CS_PIN=18
	-DCC1101_GDO0=33
	-DCC1101_GDO2=34
	-DGPS_SERIAL_TX=40
	-DGPS_SERIAL_RX=39
	-DGPS_BAUD=9600
	-DTXLED=1
	-DRXLED=47
	-DLED_ON=HIGH
	-DLED_OFF=LOW
	-DIR_TX_PINS='{{"IR TX", 1}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DIR_RX_PINS='{{"IR RX", 47}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DRF_TX_PINS='{{"M5 RF433T", GROVE_SDA}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DRF_RX_PINS='{{"M5 RF433R", GROVE_SCL}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DI2S_SCK_PIN=41
	-DI2S_WS_PIN=42
	-DI2S_SD_PIN=2
	-DJOY_X_PIN=4
	-DJOY_Y_PIN=5
	-DJOY_BTN_PIN=6
	-DLORA_SCK=12
	-DLORA_MISO=13
	-DLORA_MOSI=11
	-DLORA_CS=19
	-DLORA_RST=20
	-DLORA_DIO0=22
	-DW5500_SCK_PIN=12
	-DW5500_MISO_PIN=13
	-DW5500_MOSI_PIN=11
	-DW5500_SS_PIN=23
	-DW5500_INT_PIN=24
	-DW5500_RST_PIN=25
	-DFP=1
	-DFM=2
	-DFG=3
	-DBTN_ALIAS='"OK"'
	-DLOAD_GLCD=1
	-DLOAD_FONT2=1
	-DLOAD_FONT4=1
	-I C:/Users/leleb/.platformio/packages/framework-arduinoespressif32/libraries/Network/src
	-I $PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries
	-DDEVICE_NAME='"ESP32-S3 DevKitC-1 (Willy)"'
build_src_flags = 
	-Wall
	-Wclobbered
	-Wempty-body
	-Wignored-qualifiers
	-Wsign-compare
	-Wno-cpp
	-Wno-overloaded-virtual
	-Wtype-limits
	-march=rv32imc
	-mabi=ilp32
build_src_filter = 
	+<*>
	+<../boards/ESP32-S3-WROOM-1-N8R2/interface.cpp>
	-<.git/>
	-<.svn/>
	-<modules/bjs_interpreter/mqjs_stdlib.c>
	-<../.pio/libdeps/${PIOENV}/ESP8266Audio/src/AudioOutputI2S.cpp>
	-<../.pio/libdeps/${PIOENV}/ESP8266Audio/src/AudioOutputI2SNoDAC.cpp>
	-<../.pio/libdeps/${PIOENV}/ESP8266Audio/src/AudioOutputSPDIF.cpp>
	-<../.pio/libdeps/${PIOENV}/mquickjs/example.c>
	-<../.pio/libdeps/${PIOENV}/mquickjs/example_stdlib.c>
	-<../.pio/libdeps/${PIOENV}/mquickjs/readline.c>
	-<../.pio/libdeps/${PIOENV}/mquickjs/readline_tty.c>
build_unflags = 
	-DARDUINO_USB_CDC_ON_BOOT=0
extra_scripts = 
	pre:scripts/patch.py
	scripts/patch_i2s.py
	pre:scripts/pre_build_current_year.py
	pre:scripts/gen_mqjs_headers.py
	pre:scripts/fix_compiler_flags.py
	post:scripts/build.py
lib_deps = 
	https://github.com/bellard/mquickjs.git
	https://github.com/bitbank2/AnimatedGIF/archive/refs/heads/master.zip
	h2zero/NimBLE-Arduino@^2.3.7
	nrf24/RF24@1.5.0
	tinyu-zhao/FFT@^0.0.1
	https://github.com/bmorcelli/rc-switch/archive/refs/heads/master.zip
	https://github.com/bmorcelli/IRremoteESP8266/archive/refs/heads/master.zip
	https://github.com/rennancockles/SimpleCLI/archive/refs/heads/master.zip
	adafruit/Adafruit NeoPixel@^1.11.0
	https://github.com/rennancockles/Arduino_MFRC522v2/archive/refs/heads/master.zip
	https://github.com/bmorcelli/ESP-ChameleonUltra/archive/refs/heads/main.zip
	https://github.com/whywilson/ESP-PN532-UART/archive/refs/heads/main.zip
	https://github.com/whywilson/ESP-PN532Killer/archive/refs/heads/master.zip
	https://github.com/whywilson/ESP-PN532BLE/archive/refs/heads/master.zip
	ESP32Async/ESPAsyncWebServer
	Bodmer/JPEGDecoder
	earlephilhower/ESP8266SAM@^1.1.0
	ESP8266Audio@^1.9.7
	fbiego/ESP32Time@^2.0.0
	arduino-libraries/NTPClient @ ^3.2.1
	https://github.com/emericklaw/Adafruit-BusIO_Bruce@1.17.2-bruce.1
	https://github.com/emericklaw/Adafruit-PN532_Bruce@1.3.3-bruce.1
	Adafruit Si4713 Library@1.2.3
	https://github.com/bmorcelli/SmartRC-CC1101-Driver-Lib/archive/refs/heads/master.zip
	https://github.com/ewpa/LibSSH-ESP32.git
	https://github.com/sayacom/WireGuard-ESP32-Arduino/archive/refs/heads/feature/esp-netif.zip
	https://github.com/huckor/BER-TLV/archive/refs/heads/master.zip
	https://github.com/bmorcelli/ESP-Amiibolink/archive/refs/heads/main.zip
	jgromes/RadioLib @ ^7.4.0
	paulstoffregen/OneWire@^2.3.8
	https://github.com/lewisxhe/XPowersLib/archive/refs/heads/master.zip
	fastled/FastLED @^3.10.3
	https://github.com/bmorcelli/ESP32-PsRamFS/archive/refs/heads/patch-1.zip
	lvgl/lvgl@8.3.11
	mikalhart/TinyGPSPlus@^1.1.0
	bblanchon/ArduinoJson@^7.4.3
	spacehuhn/SimpleCLI@^1.1.4
lib_ignore = 
	SmartRC-CC1101-Driver-Lib/examples
	ESPAsyncTCP
	RPAsyncTCP

[env:test]
platform = espressif32
board = ESP32-S3-DevKitC-1-N8R2
framework = arduino
test_framework = unity
test_build_src = yes
build_src_filter = 
	+<test/>
	+<src/>
	-<src/main.cpp>
	-<src/modules/>
build_flags = 
	-DWILLY_VERSION='"1.0.0"'
	-DCORE_DEBUG_LEVEL=4
	-DLV_TICK_CUSTOM=1
	-DARDUINO_RUNNING_CORE=1
	-DTFT_eSPI_VERSION=2.5.43
	-I lib/mquickjs_headers
	-DEEPROMSIZE=128
	-DLH=8
	-DLW=6
	-Os
	-ffunction-sections
	-fdata-sections
	-Wl,--print-memory-usage
	-Wl,--gc-sections
	-Wl,--allow-multiple-definition
	-DGIT_COMMIT_HASH='"Homebrew"'
	-DFASTLED_RMT_BUILTIN_DRIVER=1
	-DCONFIG_ASYNC_TCP_STACK_SIZE=4096
	-DCONFIG_ASYNC_TCP_RUNNING_CORE=1
	-DCONFIG_ASYNC_TCP_USE_WDT=0
	-DGEN_MQJS_HEADERS
	-Iinclude
	-Isrc
	-Iboards/ESP32-S3-WROOM-1-N16R8
	-Ilib/HAL
	-Ilib/TFT_eSPI
	-Ilib/TFT_eSPI
	-Wno-narrowing
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DRGB_LED=48
	-DHAS_RGB_LED=1
	-DLED_COUNT=1
	-DLED_TYPE=WS2812B
	-DLED_ORDER=GRB
	-DLED_COLOR_STEP=5
	-DLED_TYPE_IS_RGBW=0
	-DGROVE_SDA=8
	-DGROVE_SCL=17
	-DSPI_SCK_PIN=12
	-DSPI_MOSI_PIN=11
	-DSPI_MISO_PIN=13
	-DSPI_SS_PIN=10
	-DUSE_HSPI_PORT=1
	-DTFT_BL=3
	-DHAS_SCREEN=1
	-DUSER_SETUP_LOADED=1
	-DILI9341_DRIVER=1
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	-DROTATION=1
	-DBACKLIGHT=3
	-DMINBRIGHT=160
	-DTFT_DISPON=0x29
	-DTFT_DISPOFF=0x28
	-DTFT_CS=10
	-DTFT_DC=9
	-DTFT_RST=14
	-DTFT_MOSI=11
	-DTFT_MISO=13
	-DTFT_SCLK=12
	-DTFT_BL=3
	-DTFT_BACKLIGHT_ON=HIGH
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=20000000
	-DSPI_READ_FREQUENCY=10000000
	-DTFT_RGB_ORDER=TFT_BGR
	-DLVGL_USE_DMA=0
	-DHAS_TOUCH=1
	-DTOUCH_CS=15
	-DTOUCH_IRQ=-1
	-DSPI_TOUCH_FREQUENCY=1000000
	-DUSE_TFT_eSPI_TOUCH=1
	-DCONFIG_SPIRAM=1
	-DSDCARD_CS=38
	-DSDCARD_SCK=12
	-DSDCARD_MISO=13
	-DSDCARD_MOSI=11
	-DNRF24_SCK_PIN=12
	-DNRF24_MISO_PIN=13
	-DNRF24_MOSI_PIN=11
	-DNRF24_SS_PIN=16
	-DNRF24_CE_PIN=21
	-DNRF24_CS_PIN=16
	-DNRF24_CS2_PIN=35
	-DNRF24_CE2_PIN=37
	-DCC1101_SCK_PIN=12
	-DCC1101_MISO_PIN=13
	-DCC1101_MOSI_PIN=11
	-DCC1101_SS_PIN=18
	-DCC1101_GDO0_PIN=33
	-DCC1101_GDO2_PIN=34
	-DCC1101_CS_PIN=18
	-DCC1101_GDO0=33
	-DCC1101_GDO2=34
	-DGPS_SERIAL_TX=40
	-DGPS_SERIAL_RX=39
	-DGPS_BAUD=9600
	-DTXLED=1
	-DRXLED=47
	-DLED_ON=HIGH
	-DLED_OFF=LOW
	-DIR_TX_PINS='{{"IR TX", 1}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DIR_RX_PINS='{{"IR RX", 47}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DRF_TX_PINS='{{"M5 RF433T", GROVE_SDA}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DRF_RX_PINS='{{"M5 RF433R", GROVE_SCL}, {"Grove W", GROVE_SCL}, {"Grove Y", GROVE_SDA}}'
	-DI2S_SCK_PIN=41
	-DI2S_WS_PIN=42
	-DI2S_SD_PIN=2
	-DJOY_X_PIN=4
	-DJOY_Y_PIN=5
	-DJOY_BTN_PIN=6
	-DLORA_SCK=12
	-DLORA_MISO=13
	-DLORA_MOSI=11
	-DLORA_CS=19
	-DLORA_RST=20
	-DLORA_DIO0=22
	-DW5500_SCK_PIN=12
	-DW5500_MISO_PIN=13
	-DW5500_MOSI_PIN=11
	-DW5500_SS_PIN=23
	-DW5500_INT_PIN=24
	-DW5500_RST_PIN=25
	-DFP=1
	-DFM=2
	-DFG=3
	-DBTN_ALIAS='"OK"'
	-DLOAD_GLCD=1
	-DLOAD_FONT2=1
	-DLOAD_FONT4=1
	-I C:/Users/leleb/.platformio/packages/framework-arduinoespressif32/libraries/Network/src
	-I $PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries
	-DDEVICE_NAME='"ESP32-S3 DevKitC-1 (Willy)"'
lib_deps = 
	https://github.com/bellard/mquickjs.git
	https://github.com/bitbank2/AnimatedGIF/archive/refs/heads/master.zip
	h2zero/NimBLE-Arduino@^2.3.7
	nrf24/RF24@1.5.0
	tinyu-zhao/FFT@^0.0.1
	https://github.com/bmorcelli/rc-switch/archive/refs/heads/master.zip
	https://github.com/bmorcelli/IRremoteESP8266/archive/refs/heads/master.zip
	https://github.com/rennancockles/SimpleCLI/archive/refs/heads/master.zip
	adafruit/Adafruit NeoPixel@^1.11.0
	https://github.com/rennancockles/Arduino_MFRC522v2/archive/refs/heads/master.zip
	https://github.com/bmorcelli/ESP-ChameleonUltra/archive/refs/heads/main.zip
	https://github.com/whywilson/ESP-PN532-UART/archive/refs/heads/main.zip
	https://github.com/whywilson/ESP-PN532Killer/archive/refs/heads/master.zip
	https://github.com/whywilson/ESP-PN532BLE/archive/refs/heads/master.zip
	ESP32Async/ESPAsyncWebServer
	Bodmer/JPEGDecoder
	earlephilhower/ESP8266SAM@^1.1.0
	ESP8266Audio@^1.9.7
	fbiego/ESP32Time@^2.0.0
	arduino-libraries/NTPClient @ ^3.2.1
	https://github.com/emericklaw/Adafruit-BusIO_Bruce@1.17.2-bruce.1
	https://github.com/emericklaw/Adafruit-PN532_Bruce@1.3.3-bruce.1
	Adafruit Si4713 Library@1.2.3
	https://github.com/bmorcelli/SmartRC-CC1101-Driver-Lib/archive/refs/heads/master.zip
	https://github.com/ewpa/LibSSH-ESP32.git
	https://github.com/huckor/BER-TLV/archive/refs/heads/master.zip
	https://github.com/bmorcelli/ESP-Amiibolink/archive/refs/heads/main.zip
	jgromes/RadioLib @ ^7.4.0
	paulstoffregen/OneWire@^2.3.8
	https://github.com/lewisxhe/XPowersLib/archive/refs/heads/master.zip
	fastled/FastLED @^3.10.3
	https://github.com/bmorcelli/ESP32-PsRamFS/archive/refs/heads/patch-1.zip
	lvgl/lvgl@8.3.11
	mikalhart/TinyGPSPlus@^1.1.0
	bblanchon/ArduinoJson@^7.4.3
	spacehuhn/SimpleCLI@^1.1.4
