// User_Setup.h - WILLY ESP S3 + ILI9341 (LCD + Touch - 06/03/2026)
#define USER_SETUP_LOADED
#define ILI9341_DRIVER

#define TFT_WIDTH 240
#define TFT_HEIGHT 320

// === PINAGEM ATUAL (LCD + Touch) ===
#define TFT_CS 10
#define TFT_DC 9
#define TFT_RST 14
#define TFT_MOSI 11
#define TFT_SCLK 12
#define TFT_MISO 13
#define TFT_BL 3

// === TOUCH HABILITADO ===
#define TOUCH_CS 15
#define TOUCH_IRQ -1

// === CONFIGURAÇÃO OBRIGATÓRIA PARA ESP32-S3 ===
#define USE_HSPI_PORT
#define TFT_SPI_PORT 1

#define SPI_FREQUENCY 20000000
#define SPI_READ_FREQUENCY 10000000
#define SPI_TOUCH_FREQUENCY 2500000

#define LOAD_GLCD
#define LOAD_FONT2
#define LOAD_FONT4
#define LOAD_FONT6
#define LOAD_FONT7
#define LOAD_FONT8
#define LOAD_GFXFF
#define SMOOTH_FONT

#define TFT_RGB_ORDER TFT_BGR
